# Generated by Django 3.2.3 on 2024-03-26 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teebay_backend', '0003_auto_20240326_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renttransaction',
            name='rental_end_date',
        ),
        migrations.RemoveField(
            model_name='renttransaction',
            name='rental_start_date',
        ),
        migrations.AddField(
            model_name='renttransaction',
            name='rent_time',
            field=models.DurationField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
