# Generated by Django 3.2.3 on 2024-03-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teebay_backend', '0004_auto_20240326_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytransaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='renttransaction',
            name='created_at',
        ),
    ]
